config/urls.py
# config/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

"""
URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  re_path(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  re_path(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  re_path(r'^blog/', include(blog_urls))
"""

from django.conf.urls import include, url, re_path
from django.contrib.auth import views as auth_views
from config import startup, views
from admin_tools.views import login_we_vote, logout_we_vote

urlpatterns = [
    re_path(r'^$', views.start_view),  # Default page if none of the other patterns work
    re_path(r'^favicon.ico$', views.favicon_view),
    re_path(r'^robots.txt$', views.robots_view),
    re_path(r'^app-ads.txt$', views.app_ads_view),
    re_path(r'^admin/', include(('admin_tools.urls', 'admin_tools'), namespace="admin_tools")),
    re_path(r'^apis/v1/', include(('apis_v1.urls', 'apis_v1'), namespace="apis_v1")),

    re_path(r'^a/', include(('analytics.urls','analytics'), namespace="analytics")),
    re_path(r'^b/', include(('ballot.urls','ballot'), namespace="ballot")),
    re_path(r'^ballotpedia/', include(('import_export_ballotpedia.urls','ballotpedia'), namespace="ballotpedia")),
    re_path(r'^bookmark/', include(('bookmark.urls','bookmark'), namespace="bookmark")),
    re_path(r'^c/', include(('candidate.urls', 'candidate'), namespace="candidate")),
    re_path(r'^campaign/', include(('campaign.urls', 'campaign'), namespace="campaign")),
    re_path(r'^e/', include(('election.urls', 'election'), namespace="election")),
    re_path(r'^office_held/', include(('office_held.urls', 'office_held'), namespace="office_held")),
    re_path(r'^representative_list/', include(('representative.urls', 'representative_list'), namespace="representative_list")),
    re_path(r'^representative/', include(('representative.urls', 'representative'), namespace="representative")),
    re_path(r'^electoral_district/', include(('electoral_district.urls', 'electoral_district'), namespace="electoral_district")),
    re_path(r'^follow/', include(('follow.urls', 'follow'), namespace="follow")),
    re_path(r'^friend/', include(('friend.urls', 'friend'), namespace="friend")),
    re_path(r'^google_custom_search/', include(('google_custom_search.urls', 'google_custom_search'), namespace="google_custom_search")),
    re_path(r'^health/', views.health_view),  # A simple health check to make sure the site is running
    re_path(r'^image/', include(('image.urls', 'image'), namespace="image")),
    re_path(r'^import_export_batches/', include(('import_export_batches.urls', 'import_export_batches'), namespace="import_export_batches")),
    re_path(r'^import_export_ctcl/', include(('import_export_ctcl.urls', 'import_export_ctcl'), namespace="import_export_ctcl")),
    re_path(r'^import_export_facebook/', include(('import_export_facebook.urls', 'import_export_facebook'), namespace="import_export_facebook")),
    re_path(r'^import_export_google_civic/', include((
        'import_export_google_civic.urls','import_export_google_civic'), namespace="import_export_google_civic")),
    re_path(r'^import_export_maplight/', include(('import_export_maplight.urls', 'import_export_maplight'), namespace="import_export_maplight")),
    re_path(r'^import_export_twitter/', include(('import_export_twitter.urls', 'import_export_twitter'), namespace="import_export_twitter")),
    re_path(r'^import_export_vote_smart/', include(('import_export_vote_smart.urls', 'import_export_vote_smart'), namespace="import_export_vote_smart")),
    re_path(r'^import_export_wikipedia/', include(('import_export_wikipedia.urls', 'import_export_wikipedia'), namespace="import_export_wikipedia")),
    re_path(r'^import_export_endorsements/', include((
        'import_export_endorsements.urls','import_export_endorsements'), namespace="import_export_endorsements")),
    re_path(r'^info/', include(('quick_info.urls', 'quick_info'), namespace="quick_info")),
    re_path(r'^issue/', include(('issue.urls', 'issue'), namespace="issue")),
    re_path(r'^m/', include(('measure.urls', 'measure'), namespace="measure")),
    re_path(r'^off/', include(('office.urls', 'office'), namespace="office")),
    re_path(r'^org/', include(('organization.urls', 'organization'), namespace="organization")),
    re_path(r'^organization_plans/', include(('donate.urls', 'organization_plans'), namespace="organization_plans")),
    re_path(r'^pl/', include(('polling_location.urls', 'polling_location'), namespace="polling_location")),
    re_path(r'^party/', include(('party.urls', 'party'), namespace="party")),
    re_path(r'^politician_list/', include(('politician.urls', 'politician_list'), namespace="politician_list")),
    re_path(r'^politician/', include(('politician.urls', 'politician'), namespace="politician")),
    re_path(r'^pos/', include(('position.urls', 'position'), namespace="position")),
    re_path(r'^retrieve_tables/', include(('retrieve_tables.urls', 'retrieve_tables'), namespace="retrieve_tables")),
    re_path(r'^scheduled_tasks/', include(('scheduled_tasks.urls', 'scheduled_tasks'), namespace="scheduled_tasks")),
    re_path(r'^share/', include(('share.urls', 'share'), namespace="share")),
    re_path(r'^sod/', include(('support_oppose_deciding.urls', 'support_oppose_deciding'), namespace="support_oppose_deciding")),
    re_path(r'^stripe_donations/', include(('stripe_donations.urls', 'stripe'), namespace="stripe_donations")),
    re_path(r'^tag/', include(('tag.urls', 'tag'), namespace="tag")),
    re_path(r'^twitter/', include(('import_export_twitter.urls', 'twitter'), namespace="twitter")),
    re_path(r'^twitter2/', include(('twitter.urls', 'twitter2'), namespace="twitter2")),
    re_path(r'^voter/', include(('voter.urls', 'voter'), namespace="voter")),
    re_path(r'^vg/', include(('voter_guide.urls', 'voter_guide'), namespace="voter_guide")),
    # Authentication
    # re_path(r'^login/$', auth_views.login, name="login"),
    re_path(r'^login/$', login_we_vote, name="login"),
    re_path(r'^logout/$', auth_views.auth_logout, name="logout"),
    re_path(r'^login_we_vote/$', login_we_vote, name="login_we_vote"),
    re_path(r'^logout_we_vote/$', logout_we_vote, name="logout_we_vote"),
    # This line provides the following patterns:
    # login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
    re_path('', include(('social_django.urls', 'social'), namespace="social")),
    # socialcomplete/facebook - See wevote_social/utils.py
]

# Execute start-up.
startup.run()

image/urls.py
# image/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

from django.conf.urls import re_path

from . import views_admin

urlpatterns = [
    re_path(r'^cache_images_locally_for_all_organizations/$', views_admin.cache_images_locally_for_all_organizations_view,
        name='cache_images_locally_for_all_organizations'),
    re_path(r'^cache_images_locally_for_all_voters/$', views_admin.cache_images_locally_for_all_voters_view,
        name='cache_images_locally_for_all_voters'),
    re_path(r'^create_resized_images_for_all_organizations/$', views_admin.create_resized_images_for_all_organizations_view,
        name='create_resized_images_for_all_organizations'),
    re_path(r'^(?P<organization_we_vote_id>wv[\w]{2}org[\w]+)/create_resized_images_for_organization/$',
        views_admin.create_resized_images_for_organization_view, name='create_resized_images_for_organization'),
    re_path(r'^(?P<voter_id>[0-9]+)/create_resized_images_for_voters/$',
        views_admin.create_resized_images_for_voters_view, name='create_resized_images_for_voters'),
    re_path(r'^(?P<candidate_we_vote_id>wv[\w]{2}cand[\w]+)/images_for_one_candidate/$',
        views_admin.images_for_one_candidate_view, name='images_for_one_candidate'),
    re_path(r'^(?P<organization_we_vote_id>wv[\w]{2}org[\w]+)/images_for_one_organization/$',
        views_admin.images_for_one_organization_view, name='images_for_one_organization'),
    re_path(r'^(?P<voter_id>[0-9]+)/images_for_one_voter/$',
        views_admin.images_for_one_voter_view, name='images_for_one_voter'),
]

issue/urls.py
# issue/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

from . import views_admin
from django.conf.urls import re_path


urlpatterns = [
    # views_admin
    re_path(r'^$', views_admin.issue_list_view, name='issue_list',),
    re_path(r'^edit/(?P<issue_we_vote_id>wv[\w]{2}issue[\w]+)/$', views_admin.issue_edit_view, name='issue_edit'),
    re_path(r'^edit_process/$', views_admin.issue_edit_process_view, name='issue_edit_process'),
    re_path(r'^delete/', views_admin.issue_delete_process_view, name='issue_delete_process'),
    re_path(r'^delete_images/$', views_admin.issue_delete_images_view, name='issue_delete_images'),
    re_path(r'^import/$',
        views_admin.issues_import_from_master_server_view, name='issues_import_from_master_server'),
    re_path(r'^organization_link_import/$',
        views_admin.organization_link_to_issue_import_from_master_server_view,
        name='organization_link_to_issue_import_from_master_server'),
    re_path(r'^new/$', views_admin.issue_new_view, name='issue_new'),
    re_path(r'^partisan_analysis/$', views_admin.issue_partisan_analysis_view, name='issue_partisan_analysis'),
    re_path(r'^summary/(?P<issue_we_vote_id>wv[\w]{2}issue[\w]+)/$', views_admin.issue_summary_view,
        name='issue_summary'),
]

sms/urls.py
# sms/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

from django.conf.urls import url

from . import views_admin


urlpatterns = [
    # url(r'^$', views_admin.batches_home_view, name='batches_home',),
    # url(r'^batch_action_list/$', views_admin.batch_action_list_view, name='batch_action_list'),
    # url(r'^batch_action_list_process/$', views_admin.batch_action_list_process_view, name='batch_action_list_process'),
    # url(r'^batch_list/$', views_admin.batch_list_view, name='batch_list'),
    # url(r'^batch_list_process/$', views_admin.batch_list_process_view, name='batch_list_process'),
]

webapp_public/urls.py
from django.conf.urls import patterns, url
from rest_framework_nested import routers

from authentication.views import AccountViewSet

router = routers.SimpleRouter()
router.register(r'accounts', AccountViewSet)

from webapp_public.views import IndexView

urlpatterns = patterns(
    '',

    url(r'^api/v1/' include(router.urls)),

    url('^.*$', IndexView.as_view(), name='index'),
)

issue/views.py
# issue/views.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

# Also see issue/views_admin.py

templates/issue/issue_edit.html
{# templates/issue/issue_edit.html #}
{% extends "template_base.html" %}

{% block title %}{% if issue %}{{ issue.issue_name }}{% else %}New Issue{% endif %}{% endblock %}

{%  block content %}
{% load template_filters %}
{% load humanize %}

<a href="{% url 'issue:issue_list' %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}">
    < Back to Values/Issues</a>

<h1>{% if issue %}Edit Issue "{{ issue.issue_name }}"{% else %}New Issue{% endif %}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url "issue:issue_edit_process" %}" method="post" class="form-horizontal" enctype="multipart/form-data">
{% csrf_token %}

<input type="hidden" name="issue_we_vote_id" value="{% if issue %}{{ issue.we_vote_id }}{% else %}{% endif %}">

<div class="form-group">
    <label for="issue_name_id" class="col-sm-3 control-label">Issue Name</label>
    <div class="col-sm-8">
        <input type="text" name="issue_name" id="issue_name_id" class="form-control"
               value="{% if issue %}{{ issue.issue_name|default_if_none:"" }}{% else %}{{ issue_name|default_if_none:"" }}{% endif %}" />
    </div>
</div>

<div class="form-group">
    <label for="hide_issue_id" class="col-sm-3 control-label"></label>
    <div class="col-sm-8">
      <input type="checkbox" name="hide_issue" id="hide_issue_id"
             value="True"
             {% if issue %}{% if issue.hide_issue %}checked{% endif %}{% elif hide_issue %}checked{% endif %} />
        Under Construction: Hide this issue from voters
    </div>
</div>

<div class="form-group">
    <label for="issue_description_id" class="col-sm-3 control-label">Issue Description</label>
    <div class="col-sm-8">
        <textarea name="issue_description"
                  class="form-control animated"
                  placeholder="Enter official issue description">{% if issue %}{{ issue.issue_description|default_if_none:"" }}{% else %}{{ issue_description|default_if_none:"" }}{% endif %}</textarea>
    </div>
</div>

<div class="form-group">
    <label for="issue_icon_local_path_id" class="col-sm-3 control-label">
      Issue Icon Local Path
      {% if issue.issue_icon_local_path %}
        <img src="https://wevote.us/img/global/svg-icons/issues/{{ issue.issue_icon_local_path }}.svg" height="20" width="20" />
      {% endif %}
    </label>
    <div class="col-sm-8">
        <input type="text" name="issue_icon_local_path" id="issue_icon_local_path_id" class="form-control"
               value="{% if issue %}{{ issue.issue_icon_local_path|default_if_none:"" }}{% else %}{{ issue_icon_local_path|default_if_none:"" }}{% endif %}" />
    </div>
</div>

<div class="form-group">
    <label for="issue_image_file_id" class="col-sm-3 control-label">Issue Image (AWS)</label>
    <div class="col-sm-8">
        <input type="file" name="issue_image_file" id="issue_image_file_id" class="form-control"
               value="{% if issue %}{{ issue.issue_image_file }}{% else %}{{ issue_image_file }}{% endif %}" />
    </div>
</div>

<div class="form-group">
    <label for="forced_sort_order_id" class="col-sm-3 control-label">Forced Sort Order</label>
    <div class="col-sm-8">
        <input type="text" name="forced_sort_order" id="forced_sort_order_id" class="form-control"
               value="{% if issue %}{{ issue.forced_sort_order|default_if_none:"" }}{% else %}{{ forced_sort_order|default_if_none:"" }}{% endif %}" />
        <label for="twitter_handle_updates_failing_id" style="font-weight: normal !important;"><span style="color: darkgray">Order by 1, 2, 3. Leave issues without an order of "0" in existing order.</span></label><br />
    </div>
</div>

<div class="form-group">
    <label for="hide_issue_id" class="col-sm-3 control-label"></label>
    <div class="col-sm-8">
      <input type="checkbox" name="considered_left" id="considered_left_id"
             value="True"
             {% if issue %}{% if issue.considered_left %}checked{% endif %}{% endif %} />
        <label for="considered_left_id" style="font-weight: normal !important;">Considered Partisan "Left" Issue</label>

      &nbsp;&nbsp;&nbsp;&nbsp;
      <input type="checkbox" name="considered_right" id="considered_right_id"
             value="True"
             {% if issue %}{% if issue.considered_right %}checked{% endif %}{% endif %} />
        <label for="considered_right_id" style="font-weight: normal !important;">Considered Partisan "Right" Issue</label>

    </div>
</div>

<div class="form-group">
    <label for="issue_image_file_id" class="col-sm-3 control-label"></label>
    <div class="col-sm-8">
        <a href="{% url 'issue:issue_list' %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}">
           cancel</a>
        <input name="submit_text" type="submit" value="{% if issue %}Update Issue{% else %}Save New Issue{% endif %}" />
    </div>
</div>

</form>


<br />
{# Show all organizations linked to this issue #}
{% if organization_list %}
    <table class="table">
     <thead>
        <tr>
            <th></th>
            <th></th>
            <th>Endorser</th>
            <th></th>
            <th>Twitter</th>
            <th>Vote Smart ID</th>
            <th>State</th>
        </tr>
     </thead>
    {% for organization in organization_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{% if organization.we_vote_hosted_profile_image_url_medium %}
                <a href="{% url 'organization:organization_edit' organization.id %}?google_civic_election_id={{ google_civic_election_id }}&candidate_we_vote_id={{ candidate_we_vote_id }}">
                    <img src="{{ organization.we_vote_hosted_profile_image_url_medium }}" width="48px" /></a>{% endif %}</td>
            <td><a href="{% url 'organization:organization_edit' organization.id %}?google_civic_election_id={{ google_civic_election_id }}&candidate_we_vote_id={{ candidate_we_vote_id }}"
                   class="u-no-break"
                   target="_blank">
                {{ organization.organization_name }} <span class="glyphicon glyphicon-new-window"></span></a><br />
                &nbsp;&nbsp;&nbsp;(<a href="{% url 'image:images_for_one_organization' organization.we_vote_id %}" target="_blank">See images</a> in new window)
            </td>
            <td>
              {% if organization.issue_analysis_done %}
                <strong>analyzed</strong>&nbsp;
              {% else %}
                <span style="color: darkgray;">not analyzed</span>
              {% endif %}
            </td>
            <td>{% if organization.organization_twitter_handle %}{{ organization.organization_twitter_handle }} <br />
                ({{ organization.twitter_followers_count|intcomma }} followers){% endif %}</td>
            <td>{% if organization.vote_smart_id %}{{ organization.vote_smart_id }}{% endif %}</td>
            <td>{{ organization.state_served_code }}</td>
        </tr>
    {% endfor %}
    </table>
    <p></p>
{% else %}
    <p>(no organizations linked to this issue)</p>
{% endif %}



<br />
{% if issue %}
    <p><a href="{% url 'issue:issue_delete_images'%}?issue_we_vote_id={{ issue.we_vote_id }}&google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}">
        Delete Cached Images</a></p>
    {% if issue.we_vote_hosted_image_url_tiny %}
        <img src="{{ issue.we_vote_hosted_image_url_tiny }}"><br />
        Tiny Image<br />
    {% endif %}

    {% if issue.we_vote_hosted_image_url_medium %}
        <img src="{{ issue.we_vote_hosted_image_url_medium }}"><br />
        Medium Image<br />
    {% endif %}

    {% if issue.we_vote_hosted_image_url_large %}
        <img src="{{ issue.we_vote_hosted_image_url_large }}"><br />
        Large Image<br />
    {% endif %}
{% else %}

{% endif %}{# End of if issue #}


{% if issue %}
  <br />
  <br />
<form action="{% url "issue:issue_delete_process" %}" method="post" class="form-horizontal">
{% csrf_token %}
  <input type="hidden" name="issue_we_vote_id" value="{{ issue.we_vote_id }}">
  <button type="submit" class="btn btn-danger">Delete Issue</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <label for="confirm_delete_id">
    <input type="checkbox" name="confirm_delete" id="confirm_delete_id" value="1" /> Check to confirm that you want to permanently delete this issue
  </label>
</form>
{% endif %}
  <br />
  <br />


<script>
    $(function() {
        $('#contest_office_id').change(function() {
            this.form.submit();
        });
    });
</script>

<style>
    .animated {
        -webkit-transition: height 0.2s;
        -moz-transition: height 0.2s;
        transition: height 0.2s;
    }
</style>
<script>
    $(function(){
        const { autosize } = window;
        autosize($('.normal'));
        autosize($('.animated'));
     }(window.$, window.autosize));
</script>


{% endblock %}

templates/issue/issue_list.html
{# templates/issue/issue_list.html #}
{% extends "template_base.html" %}

{% block title %}Values/Issues{% endblock %}

{%  block content %}
{% load template_filters %}
{% load humanize %}

<h1>Values/Issues</h1>

<form name="issue_choose_election" method="get" action="{% url 'issue:issue_list' %}">
    {% csrf_token %}

    <a href="{% url 'issue:issue_new' %}?google_civic_election_id={{ google_civic_election_id }}">Add New Issue</a><br />

    {% if election_list %}
    <select id="google_civic_election_id" name="google_civic_election_id">
        <option value="0" {% if 0 == google_civic_election_id|convert_to_int %} selected="selected"{% endif %}>
            -- Filter by Election --</option>
        {% for one_election in election_list %}
        <option value="{{ one_election.google_civic_election_id }}"
                {% if one_election.google_civic_election_id|slugify == google_civic_election_id|slugify %} selected="selected"{% endif %}>
            {% if one_election.state_code %}{{ one_election.state_code }} {% endif %}
            {{ one_election.election_day_text }}: {{ one_election.election_name }} - {{ one_election.google_civic_election_id }}</option>
        {% endfor %}
    </select>
    {% endif %}{# End of if election_list #}

    {# Default to showing only upcoming elections #}
    <label for="show_all_elections_id">
      <input type="checkbox" name="show_all_elections" id="show_all_elections_id" value="1"
             {% if show_all_elections %}checked{% endif %} /> Include Past Elections
    </label>
    &nbsp;&nbsp;&nbsp;&nbsp;

    {% if state_list %}
        <select id="state_code_id" name="state_code">
            <option value="">
                -- Filter by State Served --</option>
        {% for key, state in state_list %}
            <option value="{{ key }}"
                    {% if key|lower == state_code|lower %} selected="selected"{% endif %}>
                {{ state }}</option>
        {% endfor %}
        </select>
        {% if state_code != "" %}
        <a href="{% url 'issue:issue_list' %}?google_civic_election_id={{ google_civic_election_id }}&issue_search={{ issue_search }}">
            show all states</a>
        {% endif %}
    {% endif %}{# End of if state_list #}

    <br />
    {% if issue_search %}
    <a href="{% url 'issue:issue_list' %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}">
         clear search</a>&nbsp;
    {% endif %}
    <input type="text" name="issue_search" id="issue_search_id" value="{{ issue_search }}" />
    <input type="submit" value="Search for Issue" />

    &nbsp;&nbsp;&nbsp;
    {% if show_hidden_issues %}
    <a href="{% url 'issue:issue_list' %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}&issue_search={{ issue_search }}&show_hidden_issues=0">
        only show issues visible to voters</a>
    {% else %}
    <a href="{% url 'issue:issue_list' %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}&issue_search={{ issue_search }}&show_hidden_issues=1">
        show hidden issues</a>
    {% endif %}

    &nbsp;&nbsp;&nbsp;
    <a href="{% url 'issue:issue_partisan_analysis' %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}"
       target="_blank">
        show partisan analysis <span class="glyphicon glyphicon-new-window"></span></a>

</form>

{% if issue_list %}
    <table class="table">
      <thead>
        <tr>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>Issue Name</th>
            <th>Forced Order</th>
            <th>Linked Org Count</th>
            <th>Followers Count</th>
            <th>Issue Description</th>
        {% if google_civic_election_id %}
            <th>Voter Guides, This Election, Linked to this Issue</th>
        {% endif %}
        </tr>
      </thead>
    {% for issue in issue_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                {% if issue.we_vote_hosted_image_url_medium %}
                    <img src="{{ issue.we_vote_hosted_image_url_medium }}" width="50" height="50" />
                {% endif %}
            </td>
            <td>
              <a href="{% url 'issue:issue_edit' issue.we_vote_id %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}"
                 class="u-no-break"
                 target="_blank">
              {% if issue.issue_icon_local_path %}
                <img src="https://wevote.us/img/global/svg-icons/issues/{{ issue.issue_icon_local_path }}.svg" height="20" width="20" />
              {% endif %}
              {{ issue.issue_name }} <span class="glyphicon glyphicon-new-window"></span></a>{% if issue.hide_issue %} - <strong>HIDDEN</strong>{% endif %}<br />
              {% if issue.considered_left %}
              <span class="glyphicon glyphicon-arrow-left"></span>
              {% elif issue.considered_right %}
              <span class="glyphicon glyphicon-arrow-right"></span>
              {% endif %}
              {{ issue.we_vote_id }}
            </td>
            <td>{{ issue.forced_sort_order|default_if_none:"" }}</td>
            <td>{{ issue.linked_organization_count|intcomma }}</td>
            <td>{{ issue.issue_followers_count|intcomma }}</td>
            <td>{{ issue.issue_description }}</td>
        {% if google_civic_election_id %}
            <td>
                <ol>
                {% for organization in issue.linked_organization_list %}
                    <li><a href="{% url 'organization:organization_position_list' organization.id %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}"
                           class="u-no-break"
                           target="_blank">{{ organization.organization_name }} <span class="glyphicon glyphicon-new-window"></span></a></li>
                {% endfor %}
                </ol>
            </td>
        {% endif %}
        </tr>
    {% endfor %}
    </table>

    <p>
        <a href="{% url 'apis_v1:issuesSyncOutView' %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}&issue_search={{ issue_search }}" target="_blank" >Export Values/Issues</a><br />
    </p>

    <p></p>
{% else %}
    <p>(no issues found)</p>
    <p>
        <a href="{% url 'issue:issue_new' %}?google_civic_election_id={{ google_civic_election_id }}">Add New Issue</a><br />
    </p>
{% endif %}

    <script>
    $(function() {
        $('#google_civic_election_id').change(function() {
            this.form.submit();
        });
    });
    $(function() {
        $('#show_all_elections_id').change(function() {
            this.form.submit();
        });
    });
    $(function() {
        $('#state_code_id').change(function() {
            this.form.submit();
        });
    });
    </script>

{% endblock %}

templates/issue/issue_summary.html
{# templates/issue/issue_summary.html #}
{% extends "template_base.html" %}

{% block title %}{% if issue %}{{ issue.issue_name }} Summary{% else %}No Candidate Found{% endif %}{% endblock %}

{%  block content %}

<a href="{% url 'issue:issue_list' %}">< Back to Candidates</a>

{% if issue %}

    <h1>{{ issue.issue_name }}</h1>
    <p>Candidate Website: <strong>{{ issue.issue_url }}</strong><br />

    </p>

{#    <p><a href="{% url 'issue:issue_edit' issue.id %}">edit</a></p>#}


{% else %}

    <h1>No Candidate Found</h1>
    Please visit the <a href="{% url 'issue:issue_list' %}">Candidate List</a> page.

{% endif %}

{% endblock %}