config/urls.py
# config/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

"""
URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  re_path(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  re_path(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  re_path(r'^blog/', include(blog_urls))
"""

from django.conf.urls import include, url, re_path
from django.contrib.auth import views as auth_views
from config import startup, views
from admin_tools.views import login_we_vote, logout_we_vote

urlpatterns = [
    re_path(r'^$', views.start_view),  # Default page if none of the other patterns work
    re_path(r'^favicon.ico$', views.favicon_view),
    re_path(r'^robots.txt$', views.robots_view),
    re_path(r'^app-ads.txt$', views.app_ads_view),
    re_path(r'^admin/', include(('admin_tools.urls', 'admin_tools'), namespace="admin_tools")),
    re_path(r'^apis/v1/', include(('apis_v1.urls', 'apis_v1'), namespace="apis_v1")),

    re_path(r'^a/', include(('analytics.urls','analytics'), namespace="analytics")),
    re_path(r'^b/', include(('ballot.urls','ballot'), namespace="ballot")),
    re_path(r'^ballotpedia/', include(('import_export_ballotpedia.urls','ballotpedia'), namespace="ballotpedia")),
    re_path(r'^bookmark/', include(('bookmark.urls','bookmark'), namespace="bookmark")),
    re_path(r'^c/', include(('candidate.urls', 'candidate'), namespace="candidate")),
    re_path(r'^campaign/', include(('campaign.urls', 'campaign'), namespace="campaign")),
    re_path(r'^e/', include(('election.urls', 'election'), namespace="election")),
    re_path(r'^office_held/', include(('office_held.urls', 'office_held'), namespace="office_held")),
    re_path(r'^representative_list/', include(('representative.urls', 'representative_list'), namespace="representative_list")),
    re_path(r'^representative/', include(('representative.urls', 'representative'), namespace="representative")),
    re_path(r'^electoral_district/', include(('electoral_district.urls', 'electoral_district'), namespace="electoral_district")),
    re_path(r'^follow/', include(('follow.urls', 'follow'), namespace="follow")),
    re_path(r'^friend/', include(('friend.urls', 'friend'), namespace="friend")),
    re_path(r'^google_custom_search/', include(('google_custom_search.urls', 'google_custom_search'), namespace="google_custom_search")),
    re_path(r'^health/', views.health_view),  # A simple health check to make sure the site is running
    re_path(r'^image/', include(('image.urls', 'image'), namespace="image")),
    re_path(r'^import_export_batches/', include(('import_export_batches.urls', 'import_export_batches'), namespace="import_export_batches")),
    re_path(r'^import_export_ctcl/', include(('import_export_ctcl.urls', 'import_export_ctcl'), namespace="import_export_ctcl")),
    re_path(r'^import_export_facebook/', include(('import_export_facebook.urls', 'import_export_facebook'), namespace="import_export_facebook")),
    re_path(r'^import_export_google_civic/', include((
        'import_export_google_civic.urls','import_export_google_civic'), namespace="import_export_google_civic")),
    re_path(r'^import_export_maplight/', include(('import_export_maplight.urls', 'import_export_maplight'), namespace="import_export_maplight")),
    re_path(r'^import_export_twitter/', include(('import_export_twitter.urls', 'import_export_twitter'), namespace="import_export_twitter")),
    re_path(r'^import_export_vote_smart/', include(('import_export_vote_smart.urls', 'import_export_vote_smart'), namespace="import_export_vote_smart")),
    re_path(r'^import_export_wikipedia/', include(('import_export_wikipedia.urls', 'import_export_wikipedia'), namespace="import_export_wikipedia")),
    re_path(r'^import_export_endorsements/', include((
        'import_export_endorsements.urls','import_export_endorsements'), namespace="import_export_endorsements")),
    re_path(r'^info/', include(('quick_info.urls', 'quick_info'), namespace="quick_info")),
    re_path(r'^issue/', include(('issue.urls', 'issue'), namespace="issue")),
    re_path(r'^m/', include(('measure.urls', 'measure'), namespace="measure")),
    re_path(r'^off/', include(('office.urls', 'office'), namespace="office")),
    re_path(r'^org/', include(('organization.urls', 'organization'), namespace="organization")),
    re_path(r'^organization_plans/', include(('donate.urls', 'organization_plans'), namespace="organization_plans")),
    re_path(r'^pl/', include(('polling_location.urls', 'polling_location'), namespace="polling_location")),
    re_path(r'^party/', include(('party.urls', 'party'), namespace="party")),
    re_path(r'^politician_list/', include(('politician.urls', 'politician_list'), namespace="politician_list")),
    re_path(r'^politician/', include(('politician.urls', 'politician'), namespace="politician")),
    re_path(r'^pos/', include(('position.urls', 'position'), namespace="position")),
    re_path(r'^retrieve_tables/', include(('retrieve_tables.urls', 'retrieve_tables'), namespace="retrieve_tables")),
    re_path(r'^scheduled_tasks/', include(('scheduled_tasks.urls', 'scheduled_tasks'), namespace="scheduled_tasks")),
    re_path(r'^share/', include(('share.urls', 'share'), namespace="share")),
    re_path(r'^sod/', include(('support_oppose_deciding.urls', 'support_oppose_deciding'), namespace="support_oppose_deciding")),
    re_path(r'^stripe_donations/', include(('stripe_donations.urls', 'stripe'), namespace="stripe_donations")),
    re_path(r'^tag/', include(('tag.urls', 'tag'), namespace="tag")),
    re_path(r'^twitter/', include(('import_export_twitter.urls', 'twitter'), namespace="twitter")),
    re_path(r'^twitter2/', include(('twitter.urls', 'twitter2'), namespace="twitter2")),
    re_path(r'^voter/', include(('voter.urls', 'voter'), namespace="voter")),
    re_path(r'^vg/', include(('voter_guide.urls', 'voter_guide'), namespace="voter_guide")),
    # Authentication
    # re_path(r'^login/$', auth_views.login, name="login"),
    re_path(r'^login/$', login_we_vote, name="login"),
    re_path(r'^logout/$', auth_views.auth_logout, name="logout"),
    re_path(r'^login_we_vote/$', login_we_vote, name="login_we_vote"),
    re_path(r'^logout_we_vote/$', logout_we_vote, name="logout_we_vote"),
    # This line provides the following patterns:
    # login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
    re_path('', include(('social_django.urls', 'social'), namespace="social")),
    # socialcomplete/facebook - See wevote_social/utils.py
]

# Execute start-up.
startup.run()

election/urls.py
# election/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

from . import views_admin
from django.conf.urls import re_path


urlpatterns = [
    # views_admin
    re_path(r'^$', views_admin.election_list_view, name='election_list',),
    re_path(r'^(?P<election_local_id>[0-9]+)/edit/$', views_admin.election_edit_view, name='election_edit'),
    re_path(r'^(?P<election_local_id>[0-9]+)/summary/$', views_admin.election_summary_view, name='election_summary'),
    re_path(r'^(?P<google_civic_election_id>[0-9]+)/summary_by_google_id/$',
        views_admin.election_summary_view, name='election_summary_by_google_id'),
    re_path(r'^ballotpedia_election_delete_process/$',
        views_admin.ballotpedia_election_delete_process_view, name='ballotpedia_election_delete_process'),
    re_path(r'^election_ballot_location_visualize/$', views_admin.election_ballot_location_visualize_view,
            name='election_ballot_location_visualize'),
    re_path(r'^election_delete_process/$', views_admin.election_delete_process_view, name='election_delete_process'),
    re_path(r'^edit_process/$', views_admin.election_edit_process_view, name='election_edit_process'),
    re_path(r'^(?P<election_local_id>[0-9]+)/election_all_ballots_retrieve/$',
        views_admin.election_all_ballots_retrieve_view, name='election_all_ballots_retrieve'),
    re_path(r'^(?P<election_local_id>[0-9]+)/election_one_ballot_retrieve/$',
        views_admin.election_one_ballot_retrieve_view, name='election_one_ballot_retrieve'),
    re_path(r'^election_migration/$', views_admin.election_migration_view, name='election_migration'),
    re_path(r'^election_remote_retrieve/$', views_admin.election_remote_retrieve_view, name='election_remote_retrieve'),
    re_path(r'^import/$',
        views_admin.elections_import_from_master_server_view, name='elections_import_from_master_server'),
    re_path(r'^nationwide_election_list/$', views_admin.nationwide_election_list_view, name='nationwide_election_list'),
    re_path(r'^test/$',
        views_admin.test_view, name='test'),
]

office/urls.py
# office/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

from django.conf.urls import re_path

from . import views_admin

urlpatterns = [
    # views_admin
    re_path(r'^$', views_admin.office_list_view, name='office_list',),
    re_path(r'^office_list_process/$', views_admin.office_list_process_view, name='office_list_process'),
    re_path(r'^compare_two_offices/$',
        views_admin.compare_two_offices_for_merge_view, name='compare_two_offices_for_merge'),
    re_path(r'^delete/$', views_admin.office_delete_process_view, name='office_delete_process'),
    re_path(r'^(?P<office_id>[0-9]+)/find_duplicate_office/$',
        views_admin.find_duplicate_office_view, name='find_duplicate_office'),
    re_path(r'^duplicate_offices/$',
        views_admin.find_and_merge_duplicate_offices_view, name='find_and_merge_duplicate_offices'),
    re_path(r'^edit_process/$', views_admin.office_edit_process_view, name='office_edit_process'),
    re_path(r'^import/$',
        views_admin.offices_import_from_master_server_view, name='offices_import_from_master_server'),
    re_path(r'^merge/$', views_admin.office_merge_process_view, name='office_merge_process'),
    re_path(r'^new/$', views_admin.office_new_view, name='office_new'),
    re_path(r'^offices_copy/$',
        views_admin.offices_copy_to_another_election_view, name='offices_copy_to_another_election'),
    re_path(r'^(?P<office_id>[0-9]+)/edit/$', views_admin.office_edit_view, name='office_edit'),
    re_path(r'^(?P<contest_office_we_vote_id>wv[\w]{2}off[\w]+)/edit/$',
        views_admin.office_edit_view, name='office_edit_we_vote_id'),
    re_path(r'^(?P<office_id>[0-9]+)/summary/$', views_admin.office_summary_view, name='office_summary'),
    re_path(r'^(?P<contest_office_we_vote_id>wv[\w]{2}off[\w]+)/summary/$',
        views_admin.office_summary_view, name='office_summary_we_vote_id'),
]

sms/urls.py
# sms/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

from django.conf.urls import url

from . import views_admin


urlpatterns = [
    # url(r'^$', views_admin.batches_home_view, name='batches_home',),
    # url(r'^batch_action_list/$', views_admin.batch_action_list_view, name='batch_action_list'),
    # url(r'^batch_action_list_process/$', views_admin.batch_action_list_process_view, name='batch_action_list_process'),
    # url(r'^batch_list/$', views_admin.batch_list_view, name='batch_list'),
    # url(r'^batch_list_process/$', views_admin.batch_list_process_view, name='batch_list_process'),
]

webapp_public/urls.py
from django.conf.urls import patterns, url
from rest_framework_nested import routers

from authentication.views import AccountViewSet

router = routers.SimpleRouter()
router.register(r'accounts', AccountViewSet)

from webapp_public.views import IndexView

urlpatterns = patterns(
    '',

    url(r'^api/v1/' include(router.urls)),

    url('^.*$', IndexView.as_view(), name='index'),
)

election/views.py
# election/views.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-


# Also see election/views_admin.py

templates/election/election_edit.html
{# templates/election/election_edit.html #}
{% extends "template_base.html" %}

{% block title %}{% if election %}{{ election.election_name  }}{% else %}Create New Election{% endif %}{% endblock %}

{%  block content %}
{% load template_filters %}

<a href="{% url 'election:election_list' %}">< Back to Elections</a>

<h1>{% if election %}Edit {{ election.election_name|default_if_none:"" }}{% else %}
    Create New Election{% endif %}</h1>
<form action="{% url "election:election_edit_process" %}" method="post" class="form-horizontal">
{% csrf_token %}

<input type="hidden" name="election_id" value="{% if election %}{{ election.id }}{% else %}0{% endif %}">
<input type="hidden" name="show_all_elections" value="{{ show_all_elections }}">
<input type="hidden" name="show_all_elections_this_year" value="{{ show_all_elections_this_year }}">

<div class="form-group">
    <label for="election_id" class="col-sm-3 control-label">Election Name{% if election %} (ID: {{ election.id }}){% endif %}</label>
    <div class="col-sm-8">
        <input type="text" name="election_name" id="election_id" class="form-control"
               value="{% if election %}{{ election.election_name }}{% endif %}" />
    </div>
</div>

<div class="form-group">
    <label for="include_in_list_for_voters_id" class="col-sm-3 control-label"></label>
    <div class="col-sm-8">
      <input type="checkbox" name="include_in_list_for_voters" id="include_in_list_for_voters_id"
             value="True"
             {% if election.include_in_list_for_voters %}checked{% endif %} />
        Show in lists of elections for voters
      &nbsp;&nbsp;&nbsp;
      <input type="checkbox" name="ignore_this_election" id="ignore_this_election_id"
             value="True"
             {% if election.ignore_this_election %}checked{% endif %} />
        Ignore this election
      &nbsp;&nbsp;&nbsp;
      <input type="checkbox" name="election_preparation_finished" id="election_preparation_finished_id"
             value="True"
             {% if election.election_preparation_finished %}checked{% endif %} />
        Election data import finished (Offices, Candidates, Ballots)
      &nbsp;&nbsp;&nbsp;
      <span class="u-no-break">
          <input type="checkbox" name="candidate_photos_finished" id="candidate_photos_finished_id"
                 value="True"
                 {% if election.candidate_photos_finished %}checked{% endif %} />
          Candidate photos finished</span>
      &nbsp;&nbsp;&nbsp;
      <input type="checkbox" name="is_national_election" id="is_national_election_id"
           value="True"
           {% if election.is_national_election %}checked{% endif %} />
        Is National Election
      <br />
      <input type="checkbox" name="use_ctcl_as_data_source" id="use_ctcl_as_data_source_id"
             value="True"
             {% if election.use_ctcl_as_data_source %}checked{% endif %} />
        Use CTCL as default data source
      &nbsp;&nbsp;&nbsp;
        Use CTCL for state codes:
      <input type="text" name="use_ctcl_as_data_source_by_state_code" id="use_ctcl_as_data_source_by_state_code_id"
             value="{{ use_ctcl_as_data_source_by_state_code|default_if_none:"" }}" />
      &nbsp;&nbsp;&nbsp;
      <input type="checkbox" name="use_google_civic_as_data_source" id="use_google_civic_as_data_source_id"
             value="True"
             {% if election.use_google_civic_as_data_source %}checked{% endif %} />
        Use Google Civic
      &nbsp;&nbsp;&nbsp;
      <span class="u-no-break">
        <input type="checkbox" name="use_ballotpedia_as_data_source" id="use_ballotpedia_as_data_source_id"
             value="True"
             {% if election.use_ballotpedia_as_data_source %}checked{% endif %} />&nbsp;Use&nbsp;Ballotpedia</span>
      &nbsp;&nbsp;&nbsp;
      <span class="u-no-break">
      <input type="checkbox" name="use_vote_usa_as_data_source" id="use_vote_usa_as_data_source_id"
             value="True"
             {% if election.use_vote_usa_as_data_source %}checked{% endif %} />&nbsp;Use&nbsp;Vote&nbsp;USA</span>
    </div>
</div>

<div class="form-group">
    <label for="google_civic_election_id_id" class="col-sm-3 control-label">Google Civic ID</label>
    <div class="col-sm-8">
        <input type="text" name="google_civic_election_id" id="google_civic_election_id_id" class="form-control"
               value="{% if election %}{{ election.google_civic_election_id|default_if_none:"" }}{% endif %}" />
    </div>
</div>

<div class="form-group">
    <label for="vote_usa_election_id_id" class="col-sm-3 control-label">Vote USA Election Id</label>
    <div class="col-sm-8">
        <input type="text" name="vote_usa_election_id" id="vote_usa_election_id_id" class="form-control"
               value="{% if election %}{{ election.vote_usa_election_id|default_if_none:"" }}{% endif %}" />
        {{ election.vote_usa_same_day_election_suffix_list }}
    </div>
</div>

<div class="form-group">
    <label for="ctcl_uuid_id" class="col-sm-3 control-label">CTCL UUID</label>
    <div class="col-sm-8">
        <input type="text" name="ctcl_uuid" id="ctcl_uuid_id" class="form-control"
               value="{% if election %}{{ election.ctcl_uuid|default_if_none:"" }}{% endif %}" />
    </div>
</div>

<div class="form-group">
    <label for="election_day_text_id" class="col-sm-3 control-label">Election Day
        <span class="no_break">(Format: "YYYY-MM-DD")</span></label>
    <div class="col-sm-8">
        <input type="text" name="election_day_text" id="election_day_text_id" class="form-control"
               value="{% if election %}{{ election.election_day_text|default_if_none:"" }}{% endif %}" />
    </div>
</div>

<div class="form-group">
    <label for="state_id" class="col-sm-3 control-label">State Code</label>
    <div class="col-sm-8">
        <input type="text" name="state_code" id="state_id" class="form-control"
               value="{% if election %}{{ election.state_code|default_if_none:"" }}{% endif %}" />
    </div>
</div>

<div class="form-group">
    <label for="ocd_division_id_id" class="col-sm-3 control-label">OCD Division ID</label>
    <div class="col-sm-8">
        <input type="text" name="ocd_division_id" id="ocd_division_id_id" class="form-control"
               value="{% if election %}{{ election.ocd_division_id|default_if_none:"" }}{% endif %}" />
    </div>
</div>

{% if not ballotpedia_election_list %}
<div class="form-group">
    <label for="ballotpedia_election_id_id" class="col-sm-3 control-label">Ballotpedia Election Id</label>
    <div class="col-sm-8">
        <input type="text" name="ballotpedia_election_id" id="ballotpedia_election_id_id" class="form-control"
               value="{% if election %}{{ election.ballotpedia_election_id|default_if_none:"" }}{% endif %}" />
    </div>
</div>

<div class="form-group">
    <label for="ballotpedia_kind_of_election_id" class="col-sm-3 control-label">Ballotpedia Kind of Election</label>
    <div class="col-sm-8">
        <input type="text" name="ballotpedia_kind_of_election" id="ballotpedia_kind_of_election_id" class="form-control"
               value="{% if election %}{{ election.ballotpedia_kind_of_election|default_if_none:"" }}{% endif %}" />
    </div>
</div>
{% endif %}{# End of if ballotpedia_election_list #}

<div class="form-group">
    <label for="internal_notes_id" class="col-sm-3 control-label">Internal Notes about Election Data Gathering</label>
    <div class="col-sm-8">
        <textarea name="internal_notes"
                  class="form-control animated"
                  id="internal_notes_id"
                  placeholder="Status of data gathering?">{% if election %}{{ election.internal_notes|default_if_none:"" }}{% else %}{{ internal_notes|default_if_none:"" }}{% endif %}</textarea>
    </div>
</div>

<div class="form-group">
    <label for="update_ballot_id" class="col-sm-3 control-label">
        {% if election %}
        <a href="{% url 'election:election_summary' election.id %}">cancel</a>
        {% else %}
        <a href="{% url 'election:election_list' %}">cancel</a>
        {% endif %}
    </label>
    <div class="col-sm-8">
        <input type="submit" class="btn btn-success" value="{% if election %}Update Election{% else %}Create New Election{% endif %}" />
    </div>
</div>

</form>



{% if ballotpedia_election_list %}
    <div class="form-group">
        <label for="ballotpedia_election_id_id" class="col-sm-3 control-label">Ballotpedia Election Id</label>
        <div class="col-sm-8">
            <table class="table">
                <tr>
                    <th></th>
                    <th>ID</th>
                    <th>District Name</th>
                    <th>District Type</th>
                    <th colspan="2">Election Type</th>
                </tr>
            {% for ballotpedia_election in ballotpedia_election_list %}
                <tr>
                    <td><span style="color: darkgray">{{ forloop.counter }}</span></td>
                    <td>{{ ballotpedia_election.ballotpedia_election_id|default_if_none:"" }}</td>
                    <td>{{ ballotpedia_election.district_name|default_if_none:"" }}</td>
                    <td><span class="u-no-break">{{ ballotpedia_election.district_type|default_if_none:"" }}</span></td>
                    <td>{{ ballotpedia_election.election_type|default_if_none:"" }}</td>
                    <td>{{ ballotpedia_election.election_description|default_if_none:"" }}</td>
                    <td>
                        <form action="{% url "election:ballotpedia_election_delete_process" %}" method="post" class="form-horizontal">
                            {% csrf_token %}
                            <input type="hidden" name="ballotpedia_election_id" value="{{ ballotpedia_election.ballotpedia_election_id }}">
                            <input type="hidden" name="google_civic_election_id" value="{{ google_civic_election_id }}">
                            <input type="hidden" name="ctcl_uuid" value="{{ ctcl_uuid }}">
                            <input type="hidden" name="state_code" value="{{ state_code }}">
                            <button type="submit" class="btn btn-outline-danger">Delete Election</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <label for="confirm_delete_id">
                              <input type="checkbox" name="confirm_delete" id="confirm_delete_id" value="1" /> Check to confirm
                            </label>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
{% endif %}{# End of if ballotpedia_election_list #}

{% if election %}
<br clear="all" />
<br />
<div>
    <form action="{% url "election:election_delete_process" %}" method="post" class="form-horizontal">
    {% csrf_token %}
      <input type="hidden" name="election_id" value="{% if election %}{{ election.id }}{% else %}0{% endif %}">
      <button type="submit" class="btn btn-outline-danger">Delete Election</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <label for="confirm_delete_id">
        <input type="checkbox" name="confirm_delete" id="confirm_delete_id" value="1" /> Check to confirm that you want to permanently delete this election
      </label>
    </form>
</div>
{% endif %}
  <br />
  <br />

{% endblock %}

templates/election/election_migration.html
{# templates/election/election_migration.html #}
{% extends "template_base.html" %}

{% block title %}Migrate Election Data{% endblock %}

{%  block content %}
{% load template_filters %}
<!-- START organization/templates/election/election_migration.html //-->

<a href="{% url 'election:election_list' %}">< Back to Elections</a>

<h1>Migrate Election Data</h1>
  <p>Only select a state if we are moving one state's election from a day where other states are also running an election.
      When a state code is selected, some data cannot be moved.</p>
<form action="{% url "election:election_migration" %}" method="post">
{% csrf_token %}

    <table>
        <tr>
            <td>From this Election:&nbsp;</td>
            <td>
{% if from_election_id %}
    <strong>
    {{ from_election.election_name }} - {{ from_election.google_civic_election_id }} - {{ from_election.election_day_text }}
    </strong>
    <input type="hidden" name="from_election_id" value="{{ from_election_id }}" />
{% else %}
    {% if from_election_list %}
    <select id="from_election_id" name="from_election_id">
        <option value="0" {% if 0 == from_election_id|convert_to_int %} selected="selected"{% endif %}>
            -- Choose Internal We Vote Election --</option>
    {% for election in from_election_list %}
        <option value="{{ election.google_civic_election_id }}"
                {% if election.google_civic_election_id|slugify == from_election_id|slugify %} selected="selected"{% endif %}>
            {{ election.election_name }} - {{ election.google_civic_election_id }} - {{ election.election_day_text }}</option>
    {% endfor %}
    </select>
    {% else %}
        "From" Election List is Missing
    {% endif %}{# End of if from_election_list #}
{% endif %}
            </td>
        </tr>
    {% if state_list %}
        <tr>
            <td>State to Migrate:&nbsp;</td>
            <td>
        <select id="from_state_code_id" name="from_state_code">
            <option value="" {% if '' == from_state_code %} selected="selected"{% endif %}>
                -- Migrate All States --</option>
        {% for key, state in state_list %}
            <option value="{{ key|lower }}"
                    {% if key|lower == from_state_code|lower %} selected="selected"{% endif %}>
                {{ state }}</option>
        {% endfor %}
        </select>
                </td>
        </tr>
    {% endif %}{# End of if state_list #}
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td>To this Election:&nbsp;</td>
            <td>
{% if to_election_id %}
    <strong>
    {{ google_civic_election.election_name }} - {{ google_civic_election.google_civic_election_id }} - {{ google_civic_election.election_day_text }}
    </strong>
    <input type="hidden" name="to_election_id" value="{{ to_election_id }}" />
{% else %}
    {% if google_civic_election_list %}
    <select id="to_election_id" name="to_election_id">
        <option value="0" {% if 0 == to_election_id|convert_to_int %} selected="selected"{% endif %}>
            -- Choose Election (Where You are Moving Data) --</option>
    {% for election in google_civic_election_list %}
        <option value="{{ election.google_civic_election_id }}"
                {% if election.google_civic_election_id|slugify == to_election_id|slugify %} selected="selected"{% endif %}>
            {{ election.election_day_text }} - {{ election.google_civic_election_id }} - {{ election.election_name }}</option>
    {% endfor %}
    </select>
    {% else %}
        "To" Election List is Missing
    {% endif %}{# End of if google_civic_election_list #}
{% endif %}
            </td>
        </tr>
    </table>


{% if from_election_id and to_election_id %}
    {% if change_now %}
      <p>
          <a href="{% url 'election:election_summary' from_election.id %}">Go Back to Election</a>
          <input type="submit" value="Analyze Migration Results" />
      </p>
    {% else %}
      <p>
          <a href="{% url 'election:election_summary' from_election.id %}">cancel</a>
          <input type="hidden" name="change_now" value="1" />
          <input type="submit" value="Migrate all now" />
      </p>
    {% endif %}
{% else %}
  <br />
    <p>This will analyze *what* data will be migrated, but does not actually move the data.</p>
    <p>
    {% if from_election_id %}
        <a href="{% url 'election:election_summary' from_election.id %}">cancel</a>
    {% else %}
        <a href="{% url 'election:election_list' %}">cancel</a>
    {% endif %}
        <input type="submit" value="Prepare to Migrate" />
    </p>
{% endif %}

</form>




<br />
{% if from_election_id %}
    {% if from_election_office_count %}
    <h5>We Vote Election: Offices</h5>
    <table>
    {% for from_election_office in from_election_office_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td colspan="3">
                <strong><a href="{% url 'office:office_summary' from_election_office.id %}">{{ from_election_office.office_name }} - {{ from_election_office.we_vote_id }}</a></strong>
            </td>
            <td>&nbsp;</td>
        </tr>

    {% endfor %}
      </table>
    {% else %}
    no offices found
    {% endif %}


    {% if from_election_candidate_count %}
    <h5>We Vote Election: Candidates</h5>
    <table>
        {% for candidate in from_election_candidate_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                {% if candidate.candidate_photo_url %}
                <img src='{{ candidate.candidate_photo_url }}' height="25px" />
                {% else %}
                    &nbsp;
                {% endif %}
            </td>
            <td><a href="{% url 'candidate:candidate_edit' candidate.id %}?google_civic_election_id={{ to_election_id }}">{{ candidate.candidate_name }} - {{ candidate.we_vote_id }}</a></td>
            <td>{{ candidate.position_count }}</td>
            <td>

            </td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
{% endif %}

{% endblock %}