config/urls.py
# config/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

"""
URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  re_path(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  re_path(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  re_path(r'^blog/', include(blog_urls))
"""

from django.conf.urls import include, url, re_path
from django.contrib.auth import views as auth_views
from config import startup, views
from admin_tools.views import login_we_vote, logout_we_vote

urlpatterns = [
    re_path(r'^$', views.start_view),  # Default page if none of the other patterns work
    re_path(r'^favicon.ico$', views.favicon_view),
    re_path(r'^robots.txt$', views.robots_view),
    re_path(r'^app-ads.txt$', views.app_ads_view),
    re_path(r'^admin/', include(('admin_tools.urls', 'admin_tools'), namespace="admin_tools")),
    re_path(r'^apis/v1/', include(('apis_v1.urls', 'apis_v1'), namespace="apis_v1")),

    re_path(r'^a/', include(('analytics.urls','analytics'), namespace="analytics")),
    re_path(r'^b/', include(('ballot.urls','ballot'), namespace="ballot")),
    re_path(r'^ballotpedia/', include(('import_export_ballotpedia.urls','ballotpedia'), namespace="ballotpedia")),
    re_path(r'^bookmark/', include(('bookmark.urls','bookmark'), namespace="bookmark")),
    re_path(r'^c/', include(('candidate.urls', 'candidate'), namespace="candidate")),
    re_path(r'^campaign/', include(('campaign.urls', 'campaign'), namespace="campaign")),
    re_path(r'^e/', include(('election.urls', 'election'), namespace="election")),
    re_path(r'^office_held/', include(('office_held.urls', 'office_held'), namespace="office_held")),
    re_path(r'^representative_list/', include(('representative.urls', 'representative_list'), namespace="representative_list")),
    re_path(r'^representative/', include(('representative.urls', 'representative'), namespace="representative")),
    re_path(r'^electoral_district/', include(('electoral_district.urls', 'electoral_district'), namespace="electoral_district")),
    re_path(r'^follow/', include(('follow.urls', 'follow'), namespace="follow")),
    re_path(r'^friend/', include(('friend.urls', 'friend'), namespace="friend")),
    re_path(r'^google_custom_search/', include(('google_custom_search.urls', 'google_custom_search'), namespace="google_custom_search")),
    re_path(r'^health/', views.health_view),  # A simple health check to make sure the site is running
    re_path(r'^image/', include(('image.urls', 'image'), namespace="image")),
    re_path(r'^import_export_batches/', include(('import_export_batches.urls', 'import_export_batches'), namespace="import_export_batches")),
    re_path(r'^import_export_ctcl/', include(('import_export_ctcl.urls', 'import_export_ctcl'), namespace="import_export_ctcl")),
    re_path(r'^import_export_facebook/', include(('import_export_facebook.urls', 'import_export_facebook'), namespace="import_export_facebook")),
    re_path(r'^import_export_google_civic/', include((
        'import_export_google_civic.urls','import_export_google_civic'), namespace="import_export_google_civic")),
    re_path(r'^import_export_maplight/', include(('import_export_maplight.urls', 'import_export_maplight'), namespace="import_export_maplight")),
    re_path(r'^import_export_twitter/', include(('import_export_twitter.urls', 'import_export_twitter'), namespace="import_export_twitter")),
    re_path(r'^import_export_vote_smart/', include(('import_export_vote_smart.urls', 'import_export_vote_smart'), namespace="import_export_vote_smart")),
    re_path(r'^import_export_wikipedia/', include(('import_export_wikipedia.urls', 'import_export_wikipedia'), namespace="import_export_wikipedia")),
    re_path(r'^import_export_endorsements/', include((
        'import_export_endorsements.urls','import_export_endorsements'), namespace="import_export_endorsements")),
    re_path(r'^info/', include(('quick_info.urls', 'quick_info'), namespace="quick_info")),
    re_path(r'^issue/', include(('issue.urls', 'issue'), namespace="issue")),
    re_path(r'^m/', include(('measure.urls', 'measure'), namespace="measure")),
    re_path(r'^off/', include(('office.urls', 'office'), namespace="office")),
    re_path(r'^org/', include(('organization.urls', 'organization'), namespace="organization")),
    re_path(r'^organization_plans/', include(('donate.urls', 'organization_plans'), namespace="organization_plans")),
    re_path(r'^pl/', include(('polling_location.urls', 'polling_location'), namespace="polling_location")),
    re_path(r'^party/', include(('party.urls', 'party'), namespace="party")),
    re_path(r'^politician_list/', include(('politician.urls', 'politician_list'), namespace="politician_list")),
    re_path(r'^politician/', include(('politician.urls', 'politician'), namespace="politician")),
    re_path(r'^pos/', include(('position.urls', 'position'), namespace="position")),
    re_path(r'^retrieve_tables/', include(('retrieve_tables.urls', 'retrieve_tables'), namespace="retrieve_tables")),
    re_path(r'^scheduled_tasks/', include(('scheduled_tasks.urls', 'scheduled_tasks'), namespace="scheduled_tasks")),
    re_path(r'^share/', include(('share.urls', 'share'), namespace="share")),
    re_path(r'^sod/', include(('support_oppose_deciding.urls', 'support_oppose_deciding'), namespace="support_oppose_deciding")),
    re_path(r'^stripe_donations/', include(('stripe_donations.urls', 'stripe'), namespace="stripe_donations")),
    re_path(r'^tag/', include(('tag.urls', 'tag'), namespace="tag")),
    re_path(r'^twitter/', include(('import_export_twitter.urls', 'twitter'), namespace="twitter")),
    re_path(r'^twitter2/', include(('twitter.urls', 'twitter2'), namespace="twitter2")),
    re_path(r'^voter/', include(('voter.urls', 'voter'), namespace="voter")),
    re_path(r'^vg/', include(('voter_guide.urls', 'voter_guide'), namespace="voter_guide")),
    # Authentication
    # re_path(r'^login/$', auth_views.login, name="login"),
    re_path(r'^login/$', login_we_vote, name="login"),
    re_path(r'^logout/$', auth_views.auth_logout, name="logout"),
    re_path(r'^login_we_vote/$', login_we_vote, name="login_we_vote"),
    re_path(r'^logout_we_vote/$', logout_we_vote, name="logout_we_vote"),
    # This line provides the following patterns:
    # login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
    re_path('', include(('social_django.urls', 'social'), namespace="social")),
    # socialcomplete/facebook - See wevote_social/utils.py
]

# Execute start-up.
startup.run()

office/urls.py
# office/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

from django.conf.urls import re_path

from . import views_admin

urlpatterns = [
    # views_admin
    re_path(r'^$', views_admin.office_list_view, name='office_list',),
    re_path(r'^office_list_process/$', views_admin.office_list_process_view, name='office_list_process'),
    re_path(r'^compare_two_offices/$',
        views_admin.compare_two_offices_for_merge_view, name='compare_two_offices_for_merge'),
    re_path(r'^delete/$', views_admin.office_delete_process_view, name='office_delete_process'),
    re_path(r'^(?P<office_id>[0-9]+)/find_duplicate_office/$',
        views_admin.find_duplicate_office_view, name='find_duplicate_office'),
    re_path(r'^duplicate_offices/$',
        views_admin.find_and_merge_duplicate_offices_view, name='find_and_merge_duplicate_offices'),
    re_path(r'^edit_process/$', views_admin.office_edit_process_view, name='office_edit_process'),
    re_path(r'^import/$',
        views_admin.offices_import_from_master_server_view, name='offices_import_from_master_server'),
    re_path(r'^merge/$', views_admin.office_merge_process_view, name='office_merge_process'),
    re_path(r'^new/$', views_admin.office_new_view, name='office_new'),
    re_path(r'^offices_copy/$',
        views_admin.offices_copy_to_another_election_view, name='offices_copy_to_another_election'),
    re_path(r'^(?P<office_id>[0-9]+)/edit/$', views_admin.office_edit_view, name='office_edit'),
    re_path(r'^(?P<contest_office_we_vote_id>wv[\w]{2}off[\w]+)/edit/$',
        views_admin.office_edit_view, name='office_edit_we_vote_id'),
    re_path(r'^(?P<office_id>[0-9]+)/summary/$', views_admin.office_summary_view, name='office_summary'),
    re_path(r'^(?P<contest_office_we_vote_id>wv[\w]{2}off[\w]+)/summary/$',
        views_admin.office_summary_view, name='office_summary_we_vote_id'),
]

position/urls.py
# position/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

from django.conf.urls import re_path
from . import views, views_admin

urlpatterns = [
    # views_admin.py
    re_path(r'^$', views_admin.position_list_view, name='position_list',),
    re_path(r'^delete/$', views_admin.position_delete_process_view, name='position_delete_process',),
    re_path(r'^edit_process/$', views_admin.position_edit_process_view, name='position_edit_process'),
    # re_path(r'^export/', views_admin.PositionsSyncOutView.as_view(), name='positions_export'),
    re_path(r'^import/$',
        views_admin.positions_import_from_master_server_view, name='positions_import_from_master_server'),
    re_path(r'^new/$', views_admin.position_new_view, name='position_new',),
    re_path(r'^relink_candidates_measures/$', views_admin.relink_candidates_measures_view,
        name='relink_candidates_measures'),
    re_path(r'^(?P<position_we_vote_id>wv[\w]{2}pos[\w]+)/edit/$', views_admin.position_edit_view, name='position_edit'),
    re_path(r'^(?P<position_we_vote_id>wv[\w]{2}pos[\w]+)/summary/$',
        views_admin.position_summary_view, name='position_summary'),
    re_path(r'^refresh_cached_position_info_for_election/',
        views_admin.refresh_cached_position_info_for_election_view,
        name='refresh_cached_position_info_for_election'),
    re_path(r'^refresh_positions_with_candidate_details/',
        views_admin.refresh_positions_with_candidate_details_for_election_view,
        name='refresh_positions_with_candidate_details_for_election'),
    re_path(r'^refresh_positions_with_office_details/',
        views_admin.refresh_positions_with_contest_office_details_for_election_view,
        name='refresh_positions_with_contest_office_details_for_election'),
    re_path(r'^refresh_positions_with_measure_details/',
        views_admin.refresh_positions_with_contest_measure_details_for_election_view,
        name='refresh_positions_with_contest_measure_details_for_election')
]

sms/urls.py
# sms/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

from django.conf.urls import url

from . import views_admin


urlpatterns = [
    # url(r'^$', views_admin.batches_home_view, name='batches_home',),
    # url(r'^batch_action_list/$', views_admin.batch_action_list_view, name='batch_action_list'),
    # url(r'^batch_action_list_process/$', views_admin.batch_action_list_process_view, name='batch_action_list_process'),
    # url(r'^batch_list/$', views_admin.batch_list_view, name='batch_list'),
    # url(r'^batch_list_process/$', views_admin.batch_list_process_view, name='batch_list_process'),
]

webapp_public/urls.py
from django.conf.urls import patterns, url
from rest_framework_nested import routers

from authentication.views import AccountViewSet

router = routers.SimpleRouter()
router.register(r'accounts', AccountViewSet)

from webapp_public.views import IndexView

urlpatterns = patterns(
    '',

    url(r'^api/v1/' include(router.urls)),

    url('^.*$', IndexView.as_view(), name='index'),
)

position/views.py
# position/views.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

templates/position/position_edit.html
{# templates/position/position_edit.html #}
{% extends "template_base.html" %}

{% block title %}{% if position %}{{ position.position_name  }}{% else %}New Position{% endif %}{% endblock %}

{%  block content %}
<h1>{% if position %}Edit {{ position.position_name }}{% else %}New Position{% endif %}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url "position:position_edit_process" %}" method="post">
{% csrf_token %}
    <input type="hidden" name="position_we_vote_id" value="{% if position %}{{ position.we_vote_id }}{% else %}{% endif %}">

{% if position %}
<p><strong>Values from Google Civic API (do not edit)</strong></p>
<p>Position ID: {{ position.we_vote_id }}</p>

{% else %}
{#    <label for="position_name_id">Position Name</label>#}
{#    <input type="text" name="position_name" id="position_name_id" value="{% if position %}{{ position.position_name }}{% endif %}" /><br />#}
{##}
{#    <label for="twitter_handle_id">Twitter </label>#}
{#    <input type="text" name="twitter_handle" id="twitter_handle_id" value="{% if position %}{{ position.twitter_handle }}{% endif %}" /><br />#}
{##}
{#    <label for="position_website_id">Position Website</label>#}
{#    <input type="text" name="position_website" id="position_website_id" value="{% if position %}{{ position.position_website }}{% endif %}" /><br />#}
{% endif %}
<p><a href="{% url 'position:position_list' %}">cancel</a>
<input type="submit" value="{% if position %}Update Position{% else %}Save New Position{% endif %}" /></p>
</form>

{% endblock %}

templates/position/position_list.html
{# templates/position/position_list.html #}
{% extends "template_base.html" %}

{% block title %}Opinions/Positions{% endblock %}

{%  block content %}
{% load template_filters %}
{% load humanize %}
<p>
  <a href="{% url 'import_export_batches:batch_list' %}?kind_of_batch=POSITION&google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}"
     target="_blank">Import New Positions <span class="glyphicon glyphicon-new-window"></span></a>
</p>

<h1>Opinions/Positions</h1>

<p>
    Also see positions listed under <a href="{% url 'organization:organization_list' %}">Endorsers</a>.
    Vote Smart ratings <a href="{% url 'import_export_vote_smart:vote_smart_rating_list' %}">here</a>.
</p>

<ul>
    <li><strong><a href="{% url 'voter_guide:voter_guide_possibility_list' %}?google_civic_election_id={{ google_civic_election_id }}"
                   target="_blank" >Review Voter Guide Possibilities <span class="glyphicon glyphicon-new-window"></span></a></strong></li>
    <li><strong><a href="{% url 'voter_guide:voter_guide_create' %}?google_civic_election_id={{ google_civic_election_id }}"
                   target="_blank">Suggest a Voter Guide <span class="glyphicon glyphicon-new-window"></span></a></strong>. Quick public tools that feeds into import_export_batch system.</li>
{% if position_list and google_civic_election_id %}
    <li>Prepare: <a href="{% url 'voter_guide:generate_voter_guides' %}?google_civic_election_id={{ google_civic_election_id }}"
                    target="_blank" >Generate Voter Guides <span class="glyphicon glyphicon-new-window"></span></a></li>
    <li>Prepare: <a href="{% url 'position:refresh_cached_position_info_for_election' %}?google_civic_election_id={{ google_civic_election_id }}"
                    target="_blank" >
        Refresh All Cached Positions for this Election <span class="glyphicon glyphicon-new-window"></span></a> (about 5 minutes)</li>
    <li>Prepare: <a href="{% url 'import_export_vote_smart:retrieve_positions_from_vote_smart_for_election' %}?google_civic_election_id={{ google_civic_election_id }}"
                    target="_blank" >
        Retrieve Positions from Vote Smart for this Election <span class="glyphicon glyphicon-new-window"></span></a></li>
{% endif %}
</ul>

<form name="organization_position_choose_election" method="get" action="{% url 'position:position_list' %}">
    {% csrf_token %}
{% if election_list %}
    <select id="google_civic_election_id" name="google_civic_election_id">
        <option value="0" {% if 0 == google_civic_election_id %} selected="selected"{% endif %}>
            -- Filter by Election --</option>
    {% for one_election in election_list %}
        <option value="{{ one_election.google_civic_election_id }}"
                {% if one_election.google_civic_election_id|slugify == google_civic_election_id|slugify %} selected="selected"{% endif %}>
            {% if one_election.state_code %}{{ one_election.state_code }} {% endif %}
            {{ one_election.election_day_text }}: {{ one_election.election_name }} - {{ one_election.google_civic_election_id }}</option>
    {% endfor %}
    </select>
{% endif %}{# End of if election_list #}

    {# Default to showing only upcoming elections #}
    <label for="show_all_elections_id">
      <input type="checkbox" name="show_all_elections" id="show_all_elections_id" value="1"
             {% if show_all_elections %}checked{% endif %} /> Include Past Elections
    </label>
    &nbsp;&nbsp;&nbsp;&nbsp;

    {% if election_years_available %}
    <select id="show_this_year_of_elections_id" name="show_this_year_of_elections">
        <option value="0" {% if 0 == show_this_year_of_elections|convert_to_int %} selected="selected"{% endif %}>
            -- Choose Year --</option>
        {% for year in election_years_available %}
        <option value="{{ year }}"
                {% if show_this_year_of_elections|slugify == year|slugify %} selected="selected"{% endif %}>
            {% if show_this_year_of_elections|slugify == year|slugify %}Limited To {% endif %}
            {{ year }}</option>
        {% endfor %}
    </select>
    {% endif %}{# End of if election_years_available #}

    {% if state_list %}
        <select id="state_code_id" name="state_code">
            <option value="">
                -- Filter by State Served --</option>
        {% for key, state in state_list %}
            <option value="{{ key }}"
                    {% if key|lower == state_code|lower %} selected="selected"{% endif %}>
                {{ state }}</option>
        {% endfor %}
        </select>
        {% if state_code != "" %}
        <a href="{% url 'position:position_list' %}?google_civic_election_id={{ google_civic_election_id }}&candidate_search={{ candidate_search }}{% if show_all_elections %}&show_all_elections=1{% endif %}">
            show all states</a>
        {% endif %}
    {% endif %}{# End of if state_list #}
    &nbsp;&nbsp;&nbsp;&nbsp;
    <label for="show_statistics_id">
      <input type="checkbox" name="show_statistics" id="show_statistics_id" value="1"
             {% if show_statistics %}checked{% endif %} /> Show Statistics
    </label>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <br />
    {% if position_search %}
        <a href="{% url 'position:position_list' %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}">
             clear search</a>&nbsp;
    {% endif %}
    <input type="text" name="position_search" id="position_search_id" value="{{ position_search }}" />
    <input type="submit" value="Search for positions" />
</form>

{% if position_list %}
    <table class="table">
      <thead>
        <tr>
            <th></th>
            <th>ID</th>
            <th>Endorser</th>
            <th>Visibility?</th>
            <th>Stance</th>
            <th>Office</th>
            <th>Candidate/Measure</th>
        </tr>
      </thead>
    {% for position in position_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{% if position.organization %}
                <a href="{% url 'organization:organization_position_edit' position.organization.id position.we_vote_id %}?google_civic_election_id={{ google_civic_election_id }}"
                   target="_blank">
                <span class="u-no-break">
                  {{ position.we_vote_id }} <span class="glyphicon glyphicon-new-window"></span>
                </span>
                </a>
                {% endif %}
            </td>
            <td>{% if position.organization %}
                <a href="{% url 'organization:organization_position_list' position.organization.id %}?google_civic_election_id={{ google_civic_election_id }}"
                   target="_blank">
                {% if position.organization.organization_name %}{{ position.organization.organization_name }}{% else %}(no org name){% endif %}
                <span class="glyphicon glyphicon-new-window"></span>
                </a>
                {% else %}
                    (organization name missing)
                {% endif %}
            </td>
            <td>{% if position.is_public_position %}<strong>Public</strong>{% else %}Friends&nbsp;Only{% endif %}</td>
            <td>
                <span class="u-no-break">
            {% if position.organization %}
                <a href="{% url 'organization:organization_position_edit' position.organization.id position.we_vote_id %}?google_civic_election_id={{ google_civic_election_id }}"
                   target="_blank">{{ position.get_stance_display }} <span class="glyphicon glyphicon-new-window"></span></a>
            {% else %}
                {{ position.get_stance_display }}
            {% endif %}
                </span>
            </td>
            <td>
                {% if position.contest_office %}
                <a href="{% url 'office:office_summary' position.contest_office.id %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}"
                   target="_blank">
                  {{ position.contest_office.office_name }}
                  <span class="glyphicon glyphicon-new-window"></span>
                </a>
                {% endif %}
            </td>
            <td>
                {% if position.candidate_campaign %}
                <a href="{% url 'candidate:candidate_summary' position.candidate_campaign.id %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}"
                   target="_blank">
                  {{ position.candidate_campaign.candidate_name }}
                  <span class="glyphicon glyphicon-new-window"></span>
                </a>
                {% elif position.contest_measure %}
                {{ position.contest_measure.measure_title }}
                {% else %}
                    (name unknown)
                {% endif %}
                <span style="color: darkgray">&nbsp;{{ position.statement_text|default_if_none:""|truncatechars:250 }}</span>
            </td>
        </tr>
    {% endfor %}
    </table>

    <p></p>
    <p>
        <a href="{% url 'apis_v1:positionsSyncOutView' %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}"
           target="_blank" >Export Positions <span class="glyphicon glyphicon-new-window"></span></a>
    </p>
    <p><a href="{% url 'position:relink_candidates_measures' %}" >Re-link Positions with Candidates or Measures</a></p>
{% else %}
    <p>(no positions found)</p>
{% endif %}
{#    <p><a href="{% url 'position:position_new' %}">Add New Position</a></p>#}

    <script>
    $(function() {
        $('#google_civic_election_id').change(function() {
            this.form.submit();
        });
    });
    $(function() {
        $('#show_all_elections_id').change(function() {
            this.form.submit();
        });
    });
    $(function() {
        $('#show_statistics_id').change(function() {
            this.form.submit();
        });
    });
    $(function() {
        $('#show_this_year_of_elections_id').change(function() {
            this.form.submit();
        });
    });
    $(function() {
        $('#state_code_id').change(function() {
            this.form.submit();
        });
    });
    </script>

{% endblock %}

templates/position/position_summary.html
{# templates/position/position_summary.html #}
{% extends "template_base.html" %}

{% block title %}{% if position %}Position Summary{% else %}No Position Found{% endif %}{% endblock %}

{%  block content %}

<a href="{% url 'position:position_list' %}">< Back to Positions</a>

{% if position %}

    <h1>Position Summary</h1>
    <p>Position ID: {{ position.we_vote_id }}<br />

    </p>

{% else %}

    <h1>No Position Found</h1>
    Please visit the <a href="{% url 'position:position_list' %}">Position List</a> page.

{% endif %}

{% endblock %}

templates/position/voter_position_list.html
{# templates/position/voter_position_list.html #}
{% extends "template_base.html" %}

{% block title %}Positions{% endblock %}

{%  block content %}
{% if position_list %}
    {% for position in position_list %}
        <div>
            {% if position.organization.id %}
            <div><span class="position_list_organization_name">{{ position.organization.organization_name }}</span>
                <input type="button" value="Following" id="following_organization_{{ position.organization.id }}"
                       class="follow_toggle_link" name="/org/{{ position.organization.id }}/unfollow/" style="display:none;" />
                <input type="button" value="+Follow" name="/org/{{ position.organization.id }}/follow/" id="not_following_organization_{{ position.organization.id }}"
                       class="follow_toggle_link" />
            </div>
            {% else %}
            <div><span class="position_list_organization_name">I Support</span></div>
            {% endif %}
            <div>{% if not position.statement_text %}
                <span class="position_list_statement_text_empty"></span>
            {% else %}
                <span class="position_list_statement_text">{{ position.statement_text }}</span>{% endif %}</div>
        </div>
        <br />

{% if position.organization.id in organizations_followed_by_voter %}
<script>
$(function() {
        var following_organization_button = '#following_organization_{{ position.organization.id }}';
        var not_following_organization_button = '#not_following_organization_{{ position.organization.id }}';
        $(following_organization_button).toggle();
        $(not_following_organization_button).toggle();
      });
</script>
{% endif %}

    {% endfor %}

<script>
$(function() {
	  $(".follow_toggle_link").live("click", function() {
	  		var url_from_href = this.name;
	  		var organization_id_string = this.id;
            var organization_id = organization_id_string.match(/\d+/)[0]; // Finds the first number and ignores the rest
		  	var not_following_organization_button = '#not_following_organization_' + organization_id; {# oppose_candidate_13 #}
		  	var following_organization_button = '#following_organization_' + organization_id;
			var dataString = 'data=none';
			//alert (dataString);return false;
			$.ajax({
              type: "GET",
              url: url_from_href,
              data: dataString,
              success: function() {
                $(following_organization_button).toggle();
                $(not_following_organization_button).toggle();
              }
            });

	    return false;
		});
	});
</script>
{% else %}
    <p>(no positions found)</p>
{% endif %}
{% endblock %}