config/urls.py
# config/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

"""
URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  re_path(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  re_path(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  re_path(r'^blog/', include(blog_urls))
"""

from django.conf.urls import include, url, re_path
from django.contrib.auth import views as auth_views
from config import startup, views
from admin_tools.views import login_we_vote, logout_we_vote

urlpatterns = [
    re_path(r'^$', views.start_view),  # Default page if none of the other patterns work
    re_path(r'^favicon.ico$', views.favicon_view),
    re_path(r'^robots.txt$', views.robots_view),
    re_path(r'^app-ads.txt$', views.app_ads_view),
    re_path(r'^admin/', include(('admin_tools.urls', 'admin_tools'), namespace="admin_tools")),
    re_path(r'^apis/v1/', include(('apis_v1.urls', 'apis_v1'), namespace="apis_v1")),

    re_path(r'^a/', include(('analytics.urls','analytics'), namespace="analytics")),
    re_path(r'^b/', include(('ballot.urls','ballot'), namespace="ballot")),
    re_path(r'^ballotpedia/', include(('import_export_ballotpedia.urls','ballotpedia'), namespace="ballotpedia")),
    re_path(r'^bookmark/', include(('bookmark.urls','bookmark'), namespace="bookmark")),
    re_path(r'^c/', include(('candidate.urls', 'candidate'), namespace="candidate")),
    re_path(r'^campaign/', include(('campaign.urls', 'campaign'), namespace="campaign")),
    re_path(r'^e/', include(('election.urls', 'election'), namespace="election")),
    re_path(r'^office_held/', include(('office_held.urls', 'office_held'), namespace="office_held")),
    re_path(r'^representative_list/', include(('representative.urls', 'representative_list'), namespace="representative_list")),
    re_path(r'^representative/', include(('representative.urls', 'representative'), namespace="representative")),
    re_path(r'^electoral_district/', include(('electoral_district.urls', 'electoral_district'), namespace="electoral_district")),
    re_path(r'^follow/', include(('follow.urls', 'follow'), namespace="follow")),
    re_path(r'^friend/', include(('friend.urls', 'friend'), namespace="friend")),
    re_path(r'^google_custom_search/', include(('google_custom_search.urls', 'google_custom_search'), namespace="google_custom_search")),
    re_path(r'^health/', views.health_view),  # A simple health check to make sure the site is running
    re_path(r'^image/', include(('image.urls', 'image'), namespace="image")),
    re_path(r'^import_export_batches/', include(('import_export_batches.urls', 'import_export_batches'), namespace="import_export_batches")),
    re_path(r'^import_export_ctcl/', include(('import_export_ctcl.urls', 'import_export_ctcl'), namespace="import_export_ctcl")),
    re_path(r'^import_export_facebook/', include(('import_export_facebook.urls', 'import_export_facebook'), namespace="import_export_facebook")),
    re_path(r'^import_export_google_civic/', include((
        'import_export_google_civic.urls','import_export_google_civic'), namespace="import_export_google_civic")),
    re_path(r'^import_export_maplight/', include(('import_export_maplight.urls', 'import_export_maplight'), namespace="import_export_maplight")),
    re_path(r'^import_export_twitter/', include(('import_export_twitter.urls', 'import_export_twitter'), namespace="import_export_twitter")),
    re_path(r'^import_export_vote_smart/', include(('import_export_vote_smart.urls', 'import_export_vote_smart'), namespace="import_export_vote_smart")),
    re_path(r'^import_export_wikipedia/', include(('import_export_wikipedia.urls', 'import_export_wikipedia'), namespace="import_export_wikipedia")),
    re_path(r'^import_export_endorsements/', include((
        'import_export_endorsements.urls','import_export_endorsements'), namespace="import_export_endorsements")),
    re_path(r'^info/', include(('quick_info.urls', 'quick_info'), namespace="quick_info")),
    re_path(r'^issue/', include(('issue.urls', 'issue'), namespace="issue")),
    re_path(r'^m/', include(('measure.urls', 'measure'), namespace="measure")),
    re_path(r'^off/', include(('office.urls', 'office'), namespace="office")),
    re_path(r'^org/', include(('organization.urls', 'organization'), namespace="organization")),
    re_path(r'^organization_plans/', include(('donate.urls', 'organization_plans'), namespace="organization_plans")),
    re_path(r'^pl/', include(('polling_location.urls', 'polling_location'), namespace="polling_location")),
    re_path(r'^party/', include(('party.urls', 'party'), namespace="party")),
    re_path(r'^politician_list/', include(('politician.urls', 'politician_list'), namespace="politician_list")),
    re_path(r'^politician/', include(('politician.urls', 'politician'), namespace="politician")),
    re_path(r'^pos/', include(('position.urls', 'position'), namespace="position")),
    re_path(r'^retrieve_tables/', include(('retrieve_tables.urls', 'retrieve_tables'), namespace="retrieve_tables")),
    re_path(r'^scheduled_tasks/', include(('scheduled_tasks.urls', 'scheduled_tasks'), namespace="scheduled_tasks")),
    re_path(r'^share/', include(('share.urls', 'share'), namespace="share")),
    re_path(r'^sod/', include(('support_oppose_deciding.urls', 'support_oppose_deciding'), namespace="support_oppose_deciding")),
    re_path(r'^stripe_donations/', include(('stripe_donations.urls', 'stripe'), namespace="stripe_donations")),
    re_path(r'^tag/', include(('tag.urls', 'tag'), namespace="tag")),
    re_path(r'^twitter/', include(('import_export_twitter.urls', 'twitter'), namespace="twitter")),
    re_path(r'^twitter2/', include(('twitter.urls', 'twitter2'), namespace="twitter2")),
    re_path(r'^voter/', include(('voter.urls', 'voter'), namespace="voter")),
    re_path(r'^vg/', include(('voter_guide.urls', 'voter_guide'), namespace="voter_guide")),
    # Authentication
    # re_path(r'^login/$', auth_views.login, name="login"),
    re_path(r'^login/$', login_we_vote, name="login"),
    re_path(r'^logout/$', auth_views.auth_logout, name="logout"),
    re_path(r'^login_we_vote/$', login_we_vote, name="login_we_vote"),
    re_path(r'^logout_we_vote/$', logout_we_vote, name="logout_we_vote"),
    # This line provides the following patterns:
    # login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
    re_path('', include(('social_django.urls', 'social'), namespace="social")),
    # socialcomplete/facebook - See wevote_social/utils.py
]

# Execute start-up.
startup.run()

representative/urls.py
# representative/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

from django.conf.urls import re_path

from . import views_admin

urlpatterns = [
    # views_admin
    re_path(r'^$', views_admin.representative_list_view, name='representative_list',),
    re_path(r'^compare_two_representatives/$',
            views_admin.compare_two_representatives_for_merge_view, name='compare_two_representatives_for_merge'),
    re_path(r'^edit_process/$', views_admin.representative_edit_process_view, name='representative_edit_process'),
    re_path(r'^delete/', views_admin.representative_delete_process_view, name='representative_delete_process'),
    re_path(r'^duplicate_representatives/$',
            views_admin.find_and_merge_duplicate_representatives_view, name='find_and_merge_duplicate_representatives'),
    re_path(r'^(?P<representative_id>[0-9]+)/find_duplicate_representative/$',
            views_admin.find_duplicate_representative_view, name='find_duplicate_representative'),
    re_path(r'^import/$',
            views_admin.representatives_import_from_master_server_view,
            name='representatives_import_from_master_server'),
    re_path(r'^politician_match/',
            views_admin.representative_politician_match_view, name='representative_politician_match'),
    re_path(r'^politician_match_this_year/', views_admin.representative_politician_match_this_year_view,
            name='representative_politician_match_this_year'),
    re_path(r'^update_representative_from_politician/', views_admin.update_representative_from_politician_view,
            name='update_representative_from_politician'),
    re_path(r'^update_from_politicians/', views_admin.update_representatives_from_politicians_view,
            name='update_representatives_from_politicians'),
    re_path(r'^merge/$', views_admin.representative_merge_process_view, name='representative_merge_process'),
    re_path(r'^new/$', views_admin.representative_new_view, name='representative_new'),
    re_path(r'^(?P<representative_id>[0-9]+)/edit/$', views_admin.representative_edit_view, name='representative_edit'),
    re_path(r'^(?P<representative_id>[0-9]+)/retrieve_photos/$',
            views_admin.representative_retrieve_photos_view, name='representative_retrieve_photos'),
]

sms/urls.py
# sms/urls.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

from django.conf.urls import url

from . import views_admin


urlpatterns = [
    # url(r'^$', views_admin.batches_home_view, name='batches_home',),
    # url(r'^batch_action_list/$', views_admin.batch_action_list_view, name='batch_action_list'),
    # url(r'^batch_action_list_process/$', views_admin.batch_action_list_process_view, name='batch_action_list_process'),
    # url(r'^batch_list/$', views_admin.batch_list_view, name='batch_list'),
    # url(r'^batch_list_process/$', views_admin.batch_list_process_view, name='batch_list_process'),
]

webapp_public/urls.py
from django.conf.urls import patterns, url
from rest_framework_nested import routers

from authentication.views import AccountViewSet

router = routers.SimpleRouter()
router.register(r'accounts', AccountViewSet)

from webapp_public.views import IndexView

urlpatterns = patterns(
    '',

    url(r'^api/v1/' include(router.urls)),

    url('^.*$', IndexView.as_view(), name='index'),
)

representative/views.py
# representative/views.py
# Brought to you by We Vote. Be good.
# -*- coding: UTF-8 -*-

templates/representative/representative_list.html
{# templates/representative/representative_list.html #}
{% extends "template_base.html" %}

{% block title %}Representatives{% endblock %}

{%  block content %}
{% load template_filters %}
{% load humanize %}

<h1>Elected Representatives</h1>

<br/>

<a href="{% url 'representative:representative_new' %}?state_code={{ state_code }}">Add New Representative</a>{% if state_code %},
<a href="{% url 'representative:find_and_merge_duplicate_representatives' %}?google_civic_election_id={{ google_civic_election_id }}&state_code={{ state_code }}" target="_blank" >
    Find and Merge Duplicate Representatives for this State <span class="glyphicon glyphicon-new-window"></span></a> (about 1 minute){% endif %}
{% if show_this_year %}
    <ul>
{#        <li>Prepare: <a href="{% url 'representative:find_and_merge_duplicate_representatives' %}?show_this_year={{ show_this_year }}&state_code={{ state_code }}"#}
{#                        target="_blank" >#}
{#        Find and Merge Duplicate Candidates for this Year <span class="glyphicon glyphicon-new-window"></span></a> (about 1 minute)</li>#}
{##}
        <li>Prepare: <a href="{% url 'representative:representative_politician_match_this_year' %}?show_this_year={{ show_this_year }}&state_code={{ state_code }}"
        target="_blank">
        Match Representatives to Politicians (and Create Politicians) for this Year <span class="glyphicon glyphicon-new-window"></span></a> (about 1 minute)</li>
        <li>Prepare: <a href="{% url 'representative:update_representatives_from_politicians' %}?show_this_year={{ show_this_year }}&state_code={{ state_code }}"
        target="_blank">
        Update Representatives from Politicians for this Year <span class="glyphicon glyphicon-new-window"></span></a> (about 1 minute)</li>
    </ul>
{% endif %}

<br/><br/>

<form name="state_code_form" method="get" action="{% url 'representative:representative_list' %}">
    {% csrf_token %}

    {% if state_list %}
        <select id="state_code_id" name="state_code">
            <option value="">
                -- Filter by State Served --</option>
        {% for key, state in state_list %}
            <option value="{{ key }}"
                    {% if key|lower == state_code|lower %} selected="selected"{% endif %}>
                {{ state }}</option>
        {% endfor %}
        </select>
    {% endif %}{# End of if state_list #}

    {% if years_available %}
    <select id="show_this_year_id" name="show_this_year">
        <option value="0" {% if 0 == show_this_year|convert_to_int %} selected="selected"{% endif %}>
            -- Choose Year --</option>
        {% for year in years_available %}
        <option value="{{ year }}"
                {% if show_this_year|slugify == year|slugify %} selected="selected"{% endif %}>
            {% if show_this_year|slugify == year|slugify %}Limited To {% endif %}
            {{ year }}</option>
        {% endfor %}
    </select>
    {% endif %}{# End of if years_available #}
    &nbsp;&nbsp;
    {% if representative_search %}
    <a href="{% url 'representative:representative_list' %}?state_code={{ state_code }}&show_representatives_with_email={{ show_representatives_with_email }}&show_all={{ show_all }}&show_this_year={{ show_this_year }}">
         clear search</a>&nbsp;
    {% endif %}
    <input type="text" name="representative_search" id="representative_search_id" value="{{ representative_search }}" />
    <input type="submit" value="Search for Representative" />
    &nbsp;&nbsp;
    <label for="show_representatives_with_email_id">
      <input type="checkbox" name="show_representatives_with_email" id="show_representatives_with_email_id" value="1"
             {% if show_representatives_with_email %}checked{% endif %} /> Has email
    </label>
    &nbsp;&nbsp;
    <label for="missing_politician_id">
      <input type="checkbox" name="missing_politician" id="missing_politician_id" value="1"
             {% if missing_politician %}checked{% endif %} /> Missing politician
    </label>
    &nbsp;&nbsp;
    <label for="show_battleground_id">
      <input type="checkbox" name="show_battleground" id="show_battleground_id" value="1"
             {% if show_battleground %}checked{% endif %} /> Show battleground races
    </label>
    &nbsp;&nbsp;
    <label for="show_all_id">
      <input type="checkbox" name="show_all" id="show_all_id" value="1"
             {% if show_all %}checked{% endif %} /> Show up to 1,000 representatives
    </label>
</form>
<br/>

{% if representative_list %}
    <table class="table">
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>Representative Name</td>
            <td>Office Held Name</td>
            <td>State</td>
            <td>Twitter Handle</td>
            <td>Email(s)</td>
            <td>ID(s)</td>
            <td>Website(s)</td>
        </tr>
    {% for representative in representative_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                {% if representative.we_vote_hosted_profile_image_url_medium %}
                <a href="{% url 'representative:representative_edit' representative.id %}?google_civic_election_id={{ google_civic_election_id }}&show_this_year={{ show_this_year }}">
                    <img src='{{ representative.we_vote_hosted_profile_image_url_medium }}' height="48px" />
                </a>
                {% endif %}
            </td>
            <td>
                <a href="{% url 'representative:representative_edit' representative.id %}?google_civic_election_id={{ google_civic_election_id }}&show_this_year={{ show_this_year }}" class="u-no-break">{{ representative.representative_name }}</a>
                <br />
                <span class="u-no-break">In office:
        {% if representative.year_in_office_2023 %}2023 {% endif %}
        {% if representative.year_in_office_2024 %}2024 {% endif %}
        {% if representative.year_in_office_2025 %}2025 {% endif %}
        {% if representative.year_in_office_2026 %}2026 {% endif %}
                </span>
            </td>
            <td>
                <a href="{% url 'office_held:office_held_summary' representative.office_held_we_vote_id %}"
                   style="display: block; width: 200px; word-wrap: break-word;"
                   target="_blank">{{ representative.office_held_name }}&nbsp;<span class="glyphicon glyphicon-new-window"></span></a>
                {% if representative.ocd_division_id %}
                    {{ representative.ocd_division_id }}
                {% endif %}
            </td>
            <td>{{ representative.state_code }}</td>
            <td>
                {% if representative.representative_twitter_handle %}<a href="https://twitter.com/{{ representative.representative_twitter_handle }}"
                    target="_blank">{{ representative.representative_twitter_handle }}</a><br />
                ({{ representative.twitter_followers_count|intcomma }} followers){% endif %}
            </td>
            <td>
                {% if representative.representative_email %}<span style="display: block; width: 150px; word-wrap: break-word;">{{ representative.representative_email }}</span>&nbsp;{% endif %}
                {% if representative.representative_email2 %}<span style="display: block; width: 150px; word-wrap: break-word;">{{ representative.representative_email2 }}</span>&nbsp;{% endif %}
                {% if representative.representative_email3 %}<span style="display: block; width: 150px; word-wrap: break-word;">{{ representative.representative_email3 }}</span>&nbsp;{% endif %}
            </td>
            <td>
                {{ representative.we_vote_id }}
                {% if representative.politician_we_vote_id %}
                    -
                    <a href="{% url 'politician:politician_we_vote_id_edit' representative.politician_we_vote_id %}?" class="u-no-break" target="_blank">
                    {{ representative.politician_we_vote_id }}&nbsp;<span class="glyphicon glyphicon-new-window"></span>
                    </a>
                {% endif %}
            </td>
            <td>
                {% if representative.wikipedia_url %}<span style="display: block; width: 200px; word-wrap: break-word;"><a href="{{ representative.wikipedia_url }}" target="_blank">{{ representative.wikipedia_url }}</a></span>&nbsp;{% endif %}
                {% if representative.representative_url %}<span style="display: block; width: 200px; word-wrap:break-word;"><a href="{{ representative.representative_url }}" target="_blank">{{ representative.representative_url }}</a></span>&nbsp;{% endif %}
                {% if representative.representative_url2 %}<span style="display: block; width: 200px; word-wrap:break-word;"><a href="{{ representative.representative_url2 }}" target="_blank">{{ representative.representative_url2 }}</a></span>&nbsp;{% endif %}
                {% if representative.representative_url3 %}<span style="display: block; width: 200px; word-wrap:break-word;"><a href="{{ representative.representative_url3 }}" target="_blank">{{ representative.representative_url3 }}</a></span>&nbsp;{% endif %}
            </td>
        </tr>
    {% endfor %}
    </table>

    <p></p>
{% else %}
    <p>(no representatives found)</p>
    <p>
        <a href="{% url 'representative:representative_new' %}?google_civic_election_id={{ google_civic_election_id }}">Add New Representative</a><br />
    </p>
{% endif %}

    <script>
        $(function() {
            $('#missing_politician_id').change(function() {
                this.form.submit();
            });
        });
        $(function() {
            $('#show_all_id').change(function() {
                this.form.submit();
            });
        });
        $(function() {
            $('#show_battleground_id').change(function() {
                this.form.submit();
            });
        });
        $(function() {
            $('#show_representatives_with_email_id').change(function() {
                this.form.submit();
            });
        });
        $(function() {
            $('#show_this_year_id').change(function() {
                this.form.submit();
            });
        });
        $(function() {
            $('#state_code_id').change(function() {
                this.form.submit();
            });
        });
    </script>

{% endblock %}

templates/representative/representative_merge_one_field_decision.html
{# templates/representative/representative_merge_one_field_decision.html #}

{% if representative1_field_value != None or representative2_field_value != None %}
<tr>
    <td>{{ field_label }}</td>
{% if conflict_status == "CONFLICT" %}
    <td><input type="radio" name="{{ field_name }}_choice" value="{{ representative1.we_vote_id }}" checked /><span class="bold-select"> {{ representative1_field_value|default_if_none:"" }}</span>&nbsp;&nbsp;</td>
    <td><input type="radio" name="{{ field_name }}_choice" value="{{ representative2.we_vote_id }}" /><span class="bold-select"> {{ representative2_field_value|default_if_none:"" }}</span></td>
{% else %}
    <td>
    {% if 'http' in representative1_field_value %}
        <a href="{{ representative1_field_value }}" target="_blank">
        {% if conflict_status == "REPRESENTATIVE1" %}<strong>{{ representative1_field_value|default_if_none:"" }}</strong>{% else %}{{ representative1_field_value|default_if_none:"" }}{% endif %}
        <span class="glyphicon glyphicon-new-window"></span>
        </a>
    {% else %}
        {% if conflict_status == "REPRESENTATIVE1" %}<strong>{{ representative1_field_value|default_if_none:"" }}</strong>{% else %}{{ representative1_field_value|default_if_none:"" }}{% endif %}
    {% endif %}
        &nbsp;&nbsp;
    </td>
    <td>
    {% if 'http' in representative2_field_value %}
        <a href="{{ representative2_field_value }}" target="_blank">
        {% if conflict_status == "REPRESENTATIVE2" %}<strong>{{ representative2_field_value|default_if_none:"" }}</strong>{% else %}{{ representative2_field_value|default_if_none:"" }}{% endif %}
        <span class="glyphicon glyphicon-new-window"></span>
        </a>
    {% else %}
        {% if conflict_status == "REPRESENTATIVE2" %}<strong>{{ representative2_field_value|default_if_none:"" }}</strong>{% else %}{{ representative2_field_value|default_if_none:"" }}{% endif %}
    {% endif %}
    </td>
{% endif %}
</tr>
{% endif %}